[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "oclock"
authors = [{name = "David Naranjo", email = "d.f.naranjohernandez@tudelft.nl"}]
dynamic = ["version", "description"]
